language: node_js
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm run init
- npm run build
script:
- xvfb-run wct -l chrome -l firefox
dist: trusty
sudo: required
